# Generated by Django 5.2 on 2025-04-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesTitr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_titr', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_defined_time', models.DateTimeField()),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.fio')),
                ('titrant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.titrant')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_replaced', models.BooleanField(default=False)),
                ('replace_source', models.CharField(blank=True, choices=[('', 'Не перезаписана'), ('lab', 'Лаборатория'), ('workshop', 'Цех')], default='', max_length=10, null=True)),
                ('v_al_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('v_titr_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('v_ppa_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('m_f_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('m_f_os', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ph_density', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('t_oc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('p_gl', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_defined_time', models.DateTimeField()),
                ('v2o5', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('h2so4', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mgso4', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('susp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.fio')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.indicator')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacing_values', to='laboratory_gmc.values')),
                ('selection_point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.selection_point')),
                ('titrant_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_in_values', to='laboratory_gmc.valuestitr')),
            ],
        ),
    ]
