# Generated by Django 5.2 on 2025-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_gmc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='dry_residue',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
