# Generated by Django 5.2 on 2025-04-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=255, unique=True)),
                ('laboratories', models.ManyToManyField(related_name='indicators', to='main.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Fio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(unique=True)),
                ('laboratories', models.ManyToManyField(related_name='fios', to='main.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='ProbeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('user_defined_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.fio')),
                ('probe_indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.probeindicator')),
            ],
        ),
        migrations.CreateModel(
            name='Probes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_defined_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.client')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.fio')),
                ('indicators', models.ManyToManyField(through='main.ProbeIndicator', to='main.indicator')),
            ],
        ),
        migrations.AddField(
            model_name='probeindicator',
            name='probe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.probes'),
        ),
        migrations.CreateModel(
            name='Selection_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_point_name', models.CharField(max_length=255, unique=True)),
                ('laboratories', models.ManyToManyField(related_name='selection_points', to='main.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='probes',
            name='selection_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.selection_point'),
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('v2o5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fe_disp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v2o5_kr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v2o5_ph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('h2so4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standart', models.BooleanField(default=False)),
                ('laboratories', models.ManyToManyField(related_name='sop', to='main.laboratory')),
                ('probes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.probes')),
            ],
        ),
        migrations.CreateModel(
            name='Titrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titrant_name', models.CharField(max_length=266, unique=True)),
                ('laboratories', models.ManyToManyField(related_name='titrants', to='main.laboratory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='probeindicator',
            unique_together={('probe', 'indicator')},
        ),
    ]
