# Generated by Django 5.2 on 2025-04-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResults',
        ),
    ]
