# Generated by Django 5.2 on 2025-04-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_analysisresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probes',
            name='indicators',
        ),
        migrations.DeleteModel(
            name='ProbeIndicator',
        ),
    ]
