# Generated by Django 5.2 on 2025-04-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_probes_indicators_delete_probeindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.probes')),
            ],
            options={
                'unique_together': {('probe', 'indicator')},
            },
        ),
        migrations.AddField(
            model_name='probes',
            name='indicators',
            field=models.ManyToManyField(through='main.ProbeIndicator', to='main.indicator'),
        ),
    ]
