# Generated by Django 5.2 on 2025-04-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_probeindicator_probes_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('user_defined_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.fio')),
                ('probe_indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.probeindicator')),
            ],
        ),
    ]
