# Generated by Django 5.2 on 2025-04-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_analysisresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='analysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.analysis'),
            preserve_default=False,
        ),
    ]
