# Generated by Django 5.2 on 2025-04-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_analysis_analysisresults_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresults',
            name='analysis',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
