# Generated by Django 5.2 on 2025-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_analysisresults_analysis_delete_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='name_value',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
