# Generated by Django 5.2 on 2025-08-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_analysisresults_name_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
