# Generated by Django 5.2 on 2025-09-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_analysisresults_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='probes',
            name='comment_for_lab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probes',
            name='name_probe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
