# Generated by Django 5.2 on 2025-10-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_probes_comment_for_lab_probes_name_probe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SOP',
        ),
    ]
