# Generated by Django 5.2 on 2025-04-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesTitrLabXA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_titr', models.DecimalField(decimal_places=7, max_digits=10)),
                ('v_titr_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('v_titr_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('v_titr_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('v_titr_4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('used_values', models.CharField(max_length=10)),
                ('user_defined_time', models.DateTimeField()),
                ('v_titr_medium', models.DecimalField(decimal_places=7, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.fio')),
                ('titrant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.titrant')),
            ],
        ),
    ]
